/*
 * Copyright (c) 2026 Hexant, LLC
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package ray.generator;

import ray.model.Game;
import ray.model.Hand;
import ray.type.Player;
import ray.type.Suit;

import java.util.*;
import static ray.type.Suit.*;

/**
 * This class compiles a Charlie shoe.
 * @author Ron.Coleman
 */
public class ShoeCompiler {
    long seed = Long.parseLong(System.getProperty("ray.seed",System.currentTimeMillis()+""));

    boolean commenting = Boolean.parseBoolean(System.getProperty("ray.comment","true"));

    String clazzBase = System.getProperty("ray.base","Shoe01");

    String clazzName = System.getProperty("ray.shoe","ShoeXyz");

    String pkgName = System.getProperty("ray.package");

    Random ran = new Random(seed);

    // One-level of indent
    final String INDENT = "    ";

    List<Player> players = new ArrayList<>(Arrays.asList(
            Player.Huey,
            Player.You,
            Player.Dewey,
            Player.Dealer));

    Map<Player,Integer> cardIndices = new HashMap<>(Map.of(
            Player.You,0,
            Player.Huey, 0,
            Player.Dewey, 0,
            Player.Dealer, 0
    ));

    Suit[] suits = {HEARTS, SPADES, DIAMONDS, CLUBS };

    public void generate(Game game) {
        prolog();

        comment("Game "+game.label);

        start(game);

        play(game);
    }

    void prolog() {
        comment(0,"");
        comment(0,"Code generated by Gameray compiler");
        comment(0,"");
        if(pkgName != null)
            write("package "+pkgName);
        write("import charlie.card.Card");
        write("import charlie.shoe."+clazzBase+";");
        write("public class "+clazzName+" extends "+ clazzBase +" { ");
        write(indent(1)+"@Override");
        write(indent(1)+"public void init() {");
        write(indent(2)+"cards.clear();");
    }

    void epilog() {
        write("}");
    }

    void play(Game game) {
        for(Player player: players) {
            Hand hand = game.whodat(player);
//            if(hand == null)
//                continue;

            if(hand == null || hand.directive == null)
                continue;
//            if(hand.directive == null || hand.directive.extraCards.isEmpty())
//                continue;

            comment(player+"");
            if(hand.directive != null) {
                switch(hand.directive.type) {
                    case 'P' -> {;
                        comment("Splitting");
                        int handno = 1;
                        for(List<String> splitHand: hand.directive.splitHands) {
                            comment("Hand "+handno);
                            for(String rank: splitHand) {
                                write(newCard(rank));
                            }
                            handno++;
                        }
                    }
                    case 'H', 'D' -> {
                        comment(hand.directive.type=='H'?"Hitting":"Doubling");
                        for(String extra: hand.directive.extraCards) {
                            write(newCard(extra));
                        }
                    }

                };
            }
            else if(hand.cards.size() >= 2) {
                for(int cardno = cardIndices.get(player); cardno < hand.cards.size(); cardno++) {
                    String rank = hand.cards.get(cardno);
                    write(newCard(rank));
                }
            }
        }
    }

    void start(Game game) {
        // Round 1
        comment("Round 1");
        for(Player player: players) {
            deal(game, player);
        }

        // Round 2
        comment("Round 2");
        for(Player player: players) {
            deal(game, player);
        }
    }

    void deal(Game game, Player player) {
        Hand hand = game.whodat(player);
        if(hand == null)
            return;

        comment(player+"");

        int cardno = cardIndices.get(player);

        if(cardno >= 2)
            return;

        String rank = hand.cards.get(cardno);

        write(newCard(rank));

        cardIndices.put(player,cardno+1);
    }

    void write(String stt) {
        System.out.println(stt);
    }

    void comment(int level,String line) {
        if(!commenting)
            return;
        write(indent(level)+"// "+line);
    }

    void comment(String line) {
        comment(2,line);
    }

    String newCard(String rank) {
        int suitno = ran.nextInt(suits.length);

        Suit suit = suits[suitno];

        return indent(2)+"cards.add(new Card("+rank+", "+suit+"));";
    }

    String indent(int level) {
        StringBuilder buffer = new StringBuilder();

        for(int i=0; i < level; i++) {
            buffer.append(INDENT);
        }

        return buffer.toString();
    }
}
