/*
 * Copyright (c) 2026 Hexant, LLC
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package ray.generator;

import ray.model.Game;
import ray.model.Hand;
import ray.type.Player;
import ray.type.Suit;

import java.util.*;
import static ray.type.Suit.*;

/**
 * This class builds a Charlie shoe.
 * @author Ron.Coleman
 */
public class ShoeBuilder {
    long seed = Long.parseLong(System.getProperty("ray.seed",System.currentTimeMillis()+""));

    boolean commenting = Boolean.parseBoolean(System.getProperty("ray.comment","true"));

    String clazzBase = System.getProperty("ray.base","Shoe01");

    String clazzName = System.getProperty("ray.shoe","ShoeXyz");

    String pkgName = System.getProperty("ray.package");

    Random ran = new Random(seed);

    // One-level of indent
    final String INDENT = "    ";

    // Players dealt in this order
    List<Player> players = new ArrayList<>(Arrays.asList(
            Player.Huey,
            Player.You,
            Player.Dewey,
            Player.Dealer));

    // Indexes of next cards
    Map<Player,Integer> cardIndices = new HashMap<>(Map.of(
            Player.You,0,
            Player.Huey, 0,
            Player.Dewey, 0,
            Player.Dealer, 0
    ));

    // Suits in play for this game
    Suit[] suits = {HEARTS, SPADES, DIAMONDS, CLUBS };

    /**
     * Generates code for a single-game shoe.
     * @param game Compiled game
     */
    public void generate(Game game) {
        prolog();

        start(game);

        play(game);

        epilog();
    }

    /**
     * Generates code for a multi-game shoe.
     * @param games Compiled games
     */
    public void generate(List<Game> games) {
        prolog();

        for(Game game: games) {
            start(game);
            play(game);
        }

        epilog();
    }

    void prolog() {
        comment(0,"");
        comment(0,"Code auto-generated by Gameray");
        comment(0,"");

        if(pkgName != null)
            write("package "+pkgName);

        write("import charlie.card.Card;");
        write("import charlie.shoe."+clazzBase+";");
        write("public class "+clazzName+" extends "+ clazzBase +" { ");
        write(indent(1)+"@Override");
        write(indent(1)+"public void init() {");
        write(indent(2)+"cards.clear();");
    }

    /**
     * Writes code generation epilog
     */
    void epilog() {
        write(indent(1)+"}");
        write("}");
        comment(0,"END generated code");
    }

    /**
     * Starts a game card sequence
     * @param game Game
     */
    void start(Game game) {
        comment("Game "+game.label);

        comment("Round 1");
        for(Player player: players) {
            deal(game, player);
        }

        comment("Round 2");
        for(Player player: players) {
            deal(game, player);
        }
    }

    /**
     * Plays a static game though the shoe sequence
     * @param game Game
     */
    void play(Game game) {
        for(Player player: players) {
            Hand hand = game.whodat(player);

            // If there is no hand, further directives, or extra cards, adios.
            if(hand == null || (hand.directive == null && hand.cards.size() == 2))
                continue;

            comment(player+"");
            if(hand.directive != null) {
                switch(hand.directive.type) {
                    case 'P' -> {
                        comment("Splitting");
                        int handno = 1;
                        for(List<String> splitHand: hand.directive.splitHands) {
                            comment("Hand "+handno);
                            for(String rank: splitHand) {
                                write(addCard(rank));
                            }
                            handno++;
                        }
                    }
                    case 'H', 'D' -> {
                        comment(hand.directive.type=='H'?"Hitting":"Doubling");
                        for(String extra: hand.directive.extraCards) {
                            write(addCard(extra));
                        }
                    }
                }
            }
            // Any extra cards written here.
            else if(hand.cards.size() >= 2) {
                comment("Hitting");
                for(int cardno = cardIndices.get(player); cardno < hand.cards.size(); cardno++) {
                    String rank = hand.cards.get(cardno);
                    write(addCard(rank));
                }
            }
        }
    }

    /**
     * Deals cards to a player for this game.
     * @param game Game
     * @param player Target player
     */
    void deal(Game game, Player player) {
        Hand hand = game.whodat(player);
        if(hand == null)
            return;

        comment(player+"");

        int index = cardIndices.get(player);

        if(index >= 2)
            return;

        String rank = hand.cards.get(index);

        write(addCard(rank));

        cardIndices.put(player,index+1);
    }

    /**
     * Generates a new card.
     * @param rank Card rank
     * @return Add card statement.
     */
    String addCard(String rank) {
        int suitno = ran.nextInt(suits.length);

        Suit suit = suits[suitno];

        return indent(2)+"cards.add(new Card("+getRank(rank)+", Card.Suit."+suit+"));";
    }

    String getRank(String rank) {
        if(rank.equals("10"))
            return rank;

        assert rank.length() == 1: "bad rank "+rank;

        switch(rank) {
            case "A" -> { return "Card.ACE";}
            case "K" -> { return "Card.KING";}
            case "Q" -> { return "Card.QUEEN";}
            case "J" -> { return "Card.JACK";}
        }

        assert Character.isDigit(rank.charAt(0)): "bad rank digit "+rank;
        assert rank.charAt(0) >= '2' && rank.charAt(0) <= '9': "invalid rank digit "+rank;
        return rank;
    }

    /**
     * Writes a statement.
     * @param stt Statement
     */
    void write(String stt) {
        System.out.println(stt);
    }

    /**
     * Writes a comment
     * @param level Indent level
     * @param line Comment
     */
    void comment(int level,String line) {
        if(!commenting)
            return;

        write(indent(level)+"// "+line);
    }

    /**
     * Writes a comment at level 2.
     * @param line Comment
     */
    void comment(String line) {
        comment(2,line);
    }

    /**
     * Indents a statement.
     * @param level Indent level
     * @return Indentation
     */
    String indent(int level) {
        return INDENT.repeat(level);
    }
}
